#!/usr/bin/env bash
# scripts/setup-branch-protection.sh
# Generated by modkit cicd module — compliance posture: startup
#
# Run ONCE after the repo is created on GitHub.
# Requires: gh CLI authenticated with admin access to the repo.
#
# Usage: ./scripts/setup-branch-protection.sh <owner/repo>

REPO="${1:?Usage: $0 owner/repo}"

gh api \
  --method PUT \
  -H "Accept: application/vnd.github+json" \
  /repos/"$REPO"/branches/main/protection \
  -f required_status_checks='{"strict":true,"contexts":["ci / build","ci / test","ci / security"]}' \
  -F enforce_admins=false \
  -f required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true}' \
  -F allow_force_pushes=false \
  -F allow_deletions=false

echo "Branch protection applied to $REPO/main"
